Add interface library.
bigladder/HPWHsim-old-fork pull request #1
Opened 2023-02-23 21:56 UTC by galanCA

## Description

Replace CMAKE flags for an interface library, as this is a more appropriate method to set flags for a library.

## Changes 

- Adds compiler-flag.cmake to contain the interface library.
- Remove c++11 flag
- This change brought up some warnings for msvc, they will be addressed in a PR to clean up warnings and set Werror.

## Test

- Runs locally
- GCC contains an error when running locally.

2023-02-23 21:58 UTC, galanCA commented
@nealkruis I don't know if I should call the interface library `hpwhsim_interface_library` or `libhpwhsim_interface_library`

2023-02-24 16:05 UTC, nealkruis requested changes

2023-02-24 16:05 UTC, nealkruis commented on src/CMakeLists.txt
> +target_compile_features(libHPWHsim PRIVATE cxx_std_17)
Does this project need C++17 features?

2023-02-24 16:05 UTC, nealkruis commented on cmake/compiler-flags.cmake
> +    -fpic       # Position Independent Code
I am realizing there is a better way to handle `fPIC`: https://github.com/bigladder/atheneum/pull/3/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR22-R24

2023-02-24 16:09 UTC, galanCA commented on src/CMakeLists.txt
> +target_compile_features(libHPWHsim PRIVATE cxx_std_17)
It will at least need C++14 or higher. But now that you mention I should let the user set up the c++ version. How can we add this to the requirements?

2023-02-24 16:13 UTC, nealkruis commented on src/CMakeLists.txt
> +target_compile_features(libHPWHsim PRIVATE cxx_std_17)
"The user"? This has to be defined by the developer for each project so that it meats the minimum feature set needed to compile.

2023-02-24 16:18 UTC, galanCA commented on src/CMakeLists.txt
> +target_compile_features(libHPWHsim PRIVATE cxx_std_17)
By the user I mean the user of the library or developer.

2024-01-16 17:52 UTC, nealkruis commented
Done on the new fork...

2024-01-16 17:52 UTC, closed without merging