Initialize tank temps
bigladder/HPWHsim-old-fork pull request #2
Opened 2023-09-11 22:32 UTC by spahrenk

## Description
- Added functions AssignTankTemperature(s) to enable setting Ts to each tank node.
- This addresses an issue that was discussed in a meeting with Chip about matching expt and sim data.
- The plural form of the function (function overloading generated a compiler warning, so different names were assigned) accepts a vector<double> representing an array of temperatures. These are distributed across all nodes using uniform scaling. No interpolation is performed, as this was deemed ambiguous (e.g., at endpoints.) A single value can instead be assigned.
- The functions were tested in debug mode using manual changes to HPWH::HPWHinit_file.
- Checks are made for an empty input vector or a null node array pointer.

## Author Progress Checklist:

- [X] Open draft pull request
    - [X] Make title clearly understandable in a standalone change log context
    - [X] Assign yourself the issue
    - [X] Add at least one label (enhancement, bug, or maintenance)
    - [ ] Link the issue(s) addressed by this PR (under "Development" in the sidebar menu) 
- [X] Make code changes (if you haven't already)
- [X] Self-review of code
    - [X] My code follows the style guidelines of this project
    - [X] I have added comments to my code, particularly in hard-to-understand areas
    - [X] I have only committed the necessary changes for this fix or feature
    - [X] I have made corresponding changes to the documentation
    - [X] My changes generate no new warnings
    - [X] I have ensured that my fix is effective or that my feature works as intended by:
        - [ ] exercising the code changes in the test framework, and/or
        - [X] manually verifying the changes (as explained in the the pull request description above)
    - [X] My changes pass all local tests
    - [X] My changes successfully passes CI checks
    - [X] Add any unit test for proof and documentation.
    - [X] Merge in main branch and address resulting conflicts and/or test failures.
- [X] Move pull request out of draft mode and assign reviewers
- [] Iterate with reviewers until all changes are approved
    - [ ] Make changes in response to reviewer comments
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
    - [ ] Re-request review in GitHub

## Reviewer Checklist:

 - [ ] Read the pull request description
 - [ ] Perform a code review on GitHub
 - [ ] Confirm all CI checks pass and there are no build warnings
 - [ ] Pull, build, and run automated tests locally
 - [ ] Perform manual tests of the fix or feature locally
 - [ ] Add any review comments, if applicable
 - [ ] Submit review in GitHub as either
     - [ ] Request changes, or
     - [ ] Approve
 - [ ] Iterate with author until all changes are approved

2023-09-18 20:56 UTC, spahrenk commented
Recent changes more carefully distribute the temperature inputs over the nodes when using setTankLayerTemperatures. It should only make a difference if the numbers of setpoint values and nodes don't divide evenly.

2023-09-29 21:10 UTC, nealkruis requested changes
@spahrenk this works as advertised, but the logic is very hard to follow. Can you take another pass with longer self-documenting variable names, and comments where it is not obvious from the names what is happening?

Partly, I'm wondering if there might be a cleaner (and more straightforward way to perform the same functionality). I wonder, too, if there are maybe some trivial cases that we can handle more simply and with less computation (e.g., number of temperatures = number of nodes).

Finally, it would be good to demonstrate this is working with some fairly basic test cases (e.g., 1 temperature with many nodes, many temperatures with 1 node) to make sure we're covering the possibilities. We really should set up unit tests in this repository, but that might be a task for a future branch.

2023-09-29 21:24 UTC, spahrenk commented
Yes, I agree with all of that. It is difficult to follow the logic and I expect that there are cases that can be handled more efficiently. I need to use a similar approach for the variable # of nodes issue, which I am already tackling on another branch. Then I will come and improve this.

2023-09-29 21:27 UTC, nealkruis commented
Thanks, @spahrenk! This change is a bit higher priority, since we'd like to get it into a release of CSE soon. If at all possible, it would be great if you can address this one first.

2023-10-02 22:40 UTC, spahrenk commented
I have attempted to improve this algorithm by adding comments. One special case is handled uniquely.

2023-10-24 19:19 UTC, spahrenk commented
I simplified the resampling function to enable sampling a single point, which is needed in some cases. It just applies the point version to each vector value. But then I generalized again to offer some possible performance gains for large, mismatched datasets, which probably reduces the performance slightly for simpler datasets. Tried to improve variable names and comment formatting.

2023-10-25 15:12 UTC, tanaya-mankad commented on test/testMaxSetpoint.cc
> +	resampleExtensive(newHeat, oldHeat);
The signature of resampleExtensive is `int resample(std::vector<double> &origValues,const std::vector<double> &newValues)` but this call seems to be using (new, old). Is this a naming issue or are the arguments reversed?

2023-10-25 15:20 UTC, tanaya-mankad commented on src/HPWH.cc
> +//-----------------------------------------------------------------------------
I really like the function level comments, but let's stick with [our standard Doxygen](https://github.com/bigladder/atheneum/blob/main/doc/guidelines.md#comments) style. (The comment style itself is up for discussion, I've used the C++ comment style with "@" tags for years so that's what I put in the BL guidelines.) See [doxygen manual](https://www.doxygen.nl/manual/commands.html) for the insanely long list of tags that can be used.

2023-10-25 15:56 UTC, tanaya-mankad commented on src/HPWH.cc
> +		double weight = fracNext - fracPrev;
I might be misinterpreting this, but it seems that for every iteration except the first one, the weight is just the inverse of nNodes - so, a constant?

2023-10-25 16:01 UTC, tanaya-mankad commented on src/HPWH.cc
> +	auto i0 = static_cast<std::size_t>(fracBegin * nNodes);
Could we do 'index' instead of 'i'?

2023-10-25 16:02 UTC, tanaya-mankad commented on src/HPWH.cc
> +	double nNodes = static_cast<double>(values.size());
nNodes doesn't have to be a double type, the calculations that use it will automatically promote it if the other operand is double.

2023-10-25 16:07 UTC, tanaya-mankad commented on src/HPWH.cc
> +	return res;
If a function returns a value and getting that value is the whole point of calling it, its name should reflect that, so maybe something like `get_weighted_resampled_value` (or better). Also `res` could be more descriptive.

2023-10-25 16:12 UTC, tanaya-mankad commented on src/HPWH.cc
> +int resample(std::vector<double> &origValues,const std::vector<double> &newValues)
The return value here seems to indicate only success or failure, so I'd choose a bool.

2023-10-25 16:48 UTC, tanaya-mankad commented on src/HPWH.cc
> +        auto xi = static_cast<double>(i);
Could we flesh out the variable names like i, j, xi, etc?

2023-10-25 17:02 UTC, spahrenk commented on test/testMaxSetpoint.cc
> +	resampleExtensive(newHeat, oldHeat);
Altered naming for clarity.

2023-10-25 17:05 UTC, spahrenk commented on src/HPWH.cc
> +	auto i0 = static_cast<std::size_t>(fracBegin * nNodes);
OK. That starts to look too verbose for my taste, though.

2023-10-25 17:06 UTC, spahrenk commented on src/HPWH.cc
> +	double nNodes = static_cast<double>(values.size());
On the other hand, there is minimal penalty for casting it during the initial assignment, so I prefer to leave it as is.

2023-10-25 17:07 UTC, spahrenk commented on src/HPWH.cc
> +int resample(std::vector<double> &origValues,const std::vector<double> &newValues)
I was intending to be consistent with the existing program, but OK. Could be some other return codes in future versions, however.

2023-10-25 17:22 UTC, spahrenk commented on src/HPWH.cc
> +		double weight = fracNext - fracPrev;
It can change on each iteration, in some cases.

2023-10-26 00:44 UTC, tanaya-mankad commented on src/HPWH.cc
> +int resample(std::vector<double> &origValues,const std::vector<double> &newValues)
When we need return codes, we can change it back. In the meantime we shouldn't need to reflect C-style practices.

2023-11-06 17:55 UTC, spahrenk commented
Needed to be merged prior to any-number-of-nodes-basic.

2023-11-06 17:58 UTC, merged